apiVersion: v1
kind: Service
metadata:
  name: apisvc
  labels:
    {{- include "secoda.labelsApi" . | nindent 4 }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 5007
      targetPort: 5007
  selector:
    {{- include "secoda.selectorLabelsApi" . | nindent 4 }}
