apiVersion: v2
name: secoda
description: Helm Chart for Secoda
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into version: 4.43.0
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application
# This is the chart version: 4.43.0
# to the chart and its templates, including the app version: 4.43.0
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 7.0.0
# This is the version: 4.43.0
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version: 4.43.0
# It is recommended to use it with quotes.
appVersion: "7.0.0"
